[Interface]
Address = 10.1.2.1/16
PrivateKey = 0O04O0wz7eyzkLMASAGMylDdnZl8m2gZyrgOvdFmO2o=

[Peer]
PublicKey = 7aJW7dWuvlN+yoVVgKoYIn0jAuNcmEsejXgibSQhGwU=
Endpoint = 144.79.188.38:51820
AllowedIPs = 10.1.0.0/16
PersistentKeepalive = 25
