[Interface]
PrivateKey = 8MisslrxAKGT73PjZrATjYTHkpayUztS48F8t3lwtEk=
Address = 10.1.2.134/32
DNS = 10.0.0.2, 1.1.1.1

[Peer]
PublicKey = RW18Gk74EdneQxil101UbULlPDNeLy4tIYdgAma1j0s=
Endpoint = 34.205.58.72:51820
AllowedIPs = 10.0.0.0/16
PersistentKeepalive = 25
